#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

echo "╔════════════════════════════════════════════╗"
echo "║   OpenVidia — Automatic Installer          ║"
echo "╚════════════════════════════════════════════╝"
echo ""

# ── 1. Python dependencies ──────────────────────
echo "▶ Installing Python dependencies..."
# Whatever installs the dependencies also has to run the app: uv puts them in a
# local venv, so the system python3 would start with nothing importable.
if command -v uv >/dev/null 2>&1; then
    uv sync --quiet
    # Absolute paths, resolved now. A desktop entry is launched by the DE with
    # a minimal PATH that usually excludes ~/.local/bin, where uv installs
    # itself — so a launcher that says `uv` finds nothing, exits, and the user
    # sees an icon that does nothing at all.
    UV_BIN="$(command -v uv)"
    RUN=("$UV_BIN" run openvidia)
    echo "  ✓ Dependencies installed (uv)"
elif command -v pip >/dev/null 2>&1; then
    pip install -e . --quiet
    PY_BIN="$(command -v python3)"
    RUN=("$PY_BIN" -m openvidia)
    echo "  ✓ Dependencies installed (pip)"
else
    echo "  ✗ You need to install uv (recommended) or pip before continuing"
    echo "    curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi
echo ""

# ── 2. Configure opencode ───────────────────────
# Only opencode. Every other CLI runs on demand with `openvidia run <cli>`,
# which sets its variables for one process and writes nothing.
echo "▶ Configuring opencode..."
"${RUN[@]}" setup || echo "  ⚠ setup reported a problem — the proxy will still start"
echo ""

# ── 3. Desktop integration (Linux only) ────────
if [[ "$(uname -s)" == "Linux" ]]; then
    echo "▶ Installing desktop entry..."
    DESKTOP_DIR="$HOME/.local/share/applications"
    ICON_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
    BIN_DIR="$HOME/.local/bin"
    mkdir -p "$DESKTOP_DIR" "$ICON_DIR" "$BIN_DIR"

    # Generate the launcher rather than patching the checked-in one. That file
    # hardcoded `uv`, so a pip install produced a desktop entry pointing at a
    # launcher that could not start the app it had just installed.
    LAUNCHER="$BIN_DIR/openvidia-desktop"
    {
        echo '#!/usr/bin/env bash'
        echo '# Generated by install.sh — every path is absolute so the entry'
        echo '# does not depend on the desktop environment PATH.'
        echo 'set -e'
        printf 'cd %q\n' "$DIR"
        printf 'exec'
        printf ' %q' "${RUN[@]}"
        printf ' "$@"\n'
    } > "$LAUNCHER"
    chmod 755 "$LAUNCHER"

    # Write the entry outright instead of sed-patching Exec=. The old
    # substitution used | as its delimiter and left the value unquoted, so an
    # install path containing |, & or a space produced a broken or mangled
    # entry — "~/My Projects" was enough to break it.
    grep -v '^Exec=' openvidia.desktop > "$DESKTOP_DIR/openvidia.desktop"
    printf 'Exec="%s"\n' "$LAUNCHER" >> "$DESKTOP_DIR/openvidia.desktop"
    chmod 644 "$DESKTOP_DIR/openvidia.desktop"

    cp openvidia/web/assets/logo.png "$ICON_DIR/openvidia.png" 2>/dev/null || true
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
    if command -v desktop-file-validate >/dev/null 2>&1; then
        desktop-file-validate "$DESKTOP_DIR/openvidia.desktop" || \
            echo "  ⚠ desktop entry failed validation (see above)"
    fi
    echo "  ✓ Desktop entry installed → $LAUNCHER"
    echo ""
fi

# ── 4. Start and verify ─────────────────────────
echo "▶ Starting proxy + desktop app..."
# No pkill: it matches by pattern (so it can hit unrelated processes), it does
# not catch the launcher wrapper, and it never checks whether anything died.
# The app frees port 1919 itself on startup, escalating if the previous
# instance ignores the polite request.
nohup "${RUN[@]}" > /dev/null 2>&1 &
LAUNCHER=$!

# Poll instead of sleeping. Startup pre-warms every key, which takes tens of
# seconds on a large pool — a fixed `sleep 3` reported failure on a perfectly
# good install.
DEADLINE=$((SECONDS + 60))
READY=""
while [ $SECONDS -lt $DEADLINE ]; do
    # -f matters: without it curl exits 0 on a 404, so READY could be set by a
    # server that was up but serving nothing.
    if curl -fsS --max-time 3 http://localhost:1919/health >/dev/null 2>&1; then
        READY=1
        break
    fi
    if ! kill -0 "$LAUNCHER" 2>/dev/null; then
        break   # launcher exited — no point waiting out the deadline
    fi
    sleep 1
done

if [ -n "$READY" ]; then
    KEYS=$(curl -fsS --max-time 5 http://localhost:1919/health | python3 -c "import sys,json; print(json.load(sys.stdin).get('keys','?'))" 2>/dev/null || echo "?")
    echo "  ✓ Proxy active — $KEYS keys on http://localhost:1919"
    echo "  ✓ Desktop app opened"
else
    echo "  ✗ Proxy did not come up. See the error with:"
    echo "      ${RUN[*]} foreground"
    exit 1
fi
echo ""

# The old banner said "Command: openvidia". With uv the entry point lives in
# .venv/bin and is never on the user's PATH, so that line named a command that
# did not exist. Print what actually works on this install.
echo "Installation complete."
echo ""
echo "  Start:      ${RUN[*]}"
echo "  Proxy:      http://localhost:1919/v1"
echo "  Dashboard:  http://localhost:1919"
echo ""
echo "  opencode is configured — select it with /model openvidia"
echo "  Other CLIs run on demand, no config files touched:"
echo "      ${RUN[*]} run codex"
echo "      ${RUN[*]} run claude"
echo "      ${RUN[*]} run grok"
